import ExplorerPage from '@/layouts/ExplorerPage';
import { Metadata } from 'next';
import React from 'react';
export const metadata: Metadata = {
  title: 'Atemu | Explorer',
  description: 'Generated by RYG Labs',
};

const Explorer = () => {
  return <ExplorerPage />;
};

export default Explorer;
