import type { Metadata } from 'next';

import ProviderApp from '@/providers';
import localFont from 'next/font/local';
import Favicon from './favicon.ico';
const PixelMono = localFont({
  src: [
    {
      path: './fonts/PixelOperatorMono.ttf',
      weight: '400',
    },
    {
      path: './fonts/PixelOperatorMono-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-family-pixel-mono',
});
export const metadata: Metadata = {
  title: 'Atemu | Flex ',
  description: 'Generated by Flex',
  icons: {
    icon: Favicon.src,
    shortcut: Favicon.src,
    apple: Favicon.src,
    other: { rel: 'apple-touch-icon-precomposed', url: Favicon.src },
  },
  keywords: ['Atemu'],
  openGraph: {
    title: 'Atemu | Flex ',
    description: 'Flex Game ',
    images: [
      {
        url: './public/assets/arts/home_bg.svg',
        width: 1200,
        height: 600,
        type: 'image/png',
      },
    ],
    locale: 'en_US',

    type: 'website',
    emails: 'karasbuilder@gmail.com',
    siteName: 'StarkPot',
  },
  twitter: {
    title: 'Atemu | Flex ',
    description: 'Flex Game ',
  },
  category: 'technology',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PixelMono.className}`}>
        <ProviderApp>{children}</ProviderApp>
      </body>
    </html>
  );
}
