name: Deploy to VPS Atemu Client 
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |

            cd atemu/Atemu-World-Frontend

            git pull

            echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker build -t karas34760/atemu-client-app:latest -f Dockerfile .
            docker push karas34760/atemu-client-app:latest


            docker stop atemu-client-app || true
            docker rm atemu-client-app || true

            # Run the Docker container with the updated image
            docker run -d --name atemu-client-app -p 3030:3030 karas34760/atemu-client-app:latest